[package]
name = "simple_histograms"
version = "0.1.0"
authors = ["thomash"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gnuplot = "0.0.34"